#!/bin/bash
if [[ -v DATABASE_URL ]]; then
    # extract the protocol
    proto="$(echo $DATABASE_URL | grep :// | sed -e's,^\(.*://\).*,\1,g')"
    # remove the protocol
    url="$(echo ${DATABASE_URL/$proto/})"
    # extract the user & password (if any)
    userpass="$(echo $url | grep @ | cut -d@ -f1)"
    # extract the username
    POSTGRES_USERNAME="$(echo $userpass | cut -d: -f1)"
    POSTGRES_PASSWORD="$(echo $userpass | cut -d: -f2)"
    # extract the host and port
    hostport="$(echo ${url/$userpass@/} | cut -d/ -f1)"
    # by request host without port
    POSTGRES_HOST="$(echo $hostport | sed -e 's,:.*,,g')"
    # by request - try to extract the port
    POSTGRES_PORT="$(echo $hostport | sed -e 's,^.*:,:,g' -e 's,.*:\([0-9]*\).*,\1,g' -e 's,[^0-9],,g')"
    # extract the path (if any)
    POSTGRES_DATABASE="$(echo $url | grep / | cut -d/ -f2-)"

    #echo "url: $url"
    #echo "  protocol: $proto"
    #echo "  username: $POSTGRES_USERNAME"
    #echo "  password: $POSTGRES_PASSWORD"
    #echo "  hostname: $POSTGRES_HOST"
    #echo "  port:     $POSTGRES_PORT"
    #echo "  database: $POSTGRES_DATABASE"
fi
POSTGRES_HOST=${POSTGRES_HOST:-"localhost"}
POSTGRES_PORT=${POSTGRES_PORT:-5432}
echo -n "Waiting for Postgres ($POSTGRES_HOST:$POSTGRES_PORT) ..."
while ! pg_isready -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" -q; do
    sleep 1
    echo -n "."
done
sleep 1;
while ! pg_isready -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" -q; do
    sleep 1
    echo -n "."
done
echo -e "\nConnected to Postgres!"
