name: Test

on:
  push:
  workflow_dispatch:

permissions: read-all

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        waiter:
          - wait-for-dynamodb
          - wait-for-mongo
          - wait-for-mysql
          - wait-for-postgresql
          - wait-for-redis
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: docker compose -p wait_for_db_${{ github.run_id }}_${{ matrix.waiter }} build
      - name: Test
        run: docker compose -p wait_for_db_${{ github.run_id }}_${{ matrix.waiter }} run --rm test ${{ matrix.waiter }}
      - name: Cleanup
        run: docker compose -p wait_for_db_${{ github.run_id }}_${{ matrix.waiter }} down -v
        if: always()
